### ISSUE TITLE
In the Readme there's a typo

### ISSUE THREAD

**Issue by lorddarkangel** [BeezyInc/hero-custom-widgets#1]
Retreave is a misspelling, change it by retrieve, please. Thanks!

**Comment by marioterron** [comment]
https://media.giphy.com/media/l1IY0geomfz09dEB2/giphy.gif

**Comment by marioterron** [comment]
> Retreave is a misspelling, change it by retrieve, please. Thanks!

https://media.giphy.com/media/l1IY0geomfz09dEB2/giphy.gif

**Comment by enriccarrion** [comment]
> Retreave is a misspelling, change it by retrieve, please. Thanks!

![Ei8us_eXkAAWRuT](https://user-images.githubusercontent.com/17001216/95569893-7b623200-0a26-11eb-8370-e0b7bda70686.jpg)
